[fonts."Berkeley Mono Nerd font"]
family = "BerkeleyMono Nerd Font"

[fonts.CommitMono]
family = "CommitMono"

[fonts.Default]
family = "Default"

[fonts."JetBrainsMono Nerd Font Mono"]
family = "JetBrainsMono Nerd Font Mono"

[fonts.MonaSpaceArgon]
family = "MonaSpace Argon"

[fonts.MonaSpaceNeon]
family = "MonaSpace Neon"


[fonts.MonaSpaceKrypton]
family = "MonaSpace Krypton"

[fonts.MonaSpaceArgonVar]
family = "MonaSpace Argon Var"

[fonts.MonaSpaceNeonVar]
family = "MonaSpace Neon Var"

[fonts.MonaSpaceKryptonVar]
family = "MonaSpace Krypton Var"

[fonts."Fira Code"]
family = "Fira Code"

[fonts."Geist Mono"]
family = "Geist Mono"

[fonts.Hack]
family = "Hack"

[fonts."IBM Plex Mono"]
family = "IBM Plex Mono"

[fonts.Lilex]
family = "Lilex"

[fonts."MD IO Trial"]
family = "MD IO Trial"

[fonts.Menlo]
family = "Menlo"

[fonts."Rec Mono"]
family = "Rec Mono Duotone"

[fonts."Roboto Mono"]
family = "Roboto Mono"

[fonts."SF Mono"]
family = "SF Mono"

[fonts."M+1Code Nerd Font Mono"]
family = "M+1Code Nerd Font Mono"

[fonts."M+1 Nerd Font"]
family = "M+1 Nerd Font"

[fonts."M+1 Nerd Font Propo"]
family = "M+1 Nerd Font Propo"
