OLED = true
appearance = "Light"
colorscheme_dark = "Brogrammer"
colorscheme_light = "Builtin Dark"
opacity = 0.88

[font]
family = "MonaSpace Krypton"

[padding]
bottom = 8
left = 8
right = 8
top = 8
