OLED = true
appearance = "Light"
colorscheme_dark = "Brogrammer"
colorscheme_light = "Builtin Dark"
opacity = 0.8

[font]
family = "JetBrainsMono Nerd Font Mono"

[padding]
bottom = 8
left = 8
right = 8
top = 8
