[[manager.prepend_keymap]]
on = ["T", "t"]
run = "plugin hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on = ["T", "T"]
run = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on = "t"
run = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[manager.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"'
'''


# Smart Tab Switch - BEGIN
[[manager.prepend_keymap]]
on = "1"
run = "plugin smart-switch --args=0"
desc = "Switch or create tab 1"

[[manager.prepend_keymap]]
on = "2"
run = "plugin smart-switch --args=1"
desc = "Switch or create tab 2"

[[manager.prepend_keymap]]
on = "3"
run = "plugin smart-switch --args=2"
desc = "Switch or create tab 3"

[[manager.prepend_keymap]]
on = "4"
run = "plugin smart-switch --args=3"
desc = "Switch or create tab 4"

[[manager.prepend_keymap]]
on = "5"
run = "plugin smart-switch --args=4"
desc = "Switch or create tab 5"

[[manager.prepend_keymap]]
on = "6"
run = "plugin smart-switch --args=5"
desc = "Switch or create tab 6"

[[manager.prepend_keymap]]
on = "7"
run = "plugin smart-switch --args=6"
desc = "Switch or create tab 7"

[[manager.prepend_keymap]]
on = "8"
run = "plugin smart-switch --args=7"
desc = "Switch or create tab 8"

[[manager.prepend_keymap]]
on = "9"
run = "plugin smart-switch --args=8"
desc = "Switch or create tab 9"
# Smart Tab Switch - END
